# -*- coding: utf-8 -*-
"""fraud_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKqu8lD6Uc9nSTuNVlhix7pF7PSISiww

# Fraud Detection & Transaction Classification

This project uses a Decision Tree model to classify transactions into:
- Normal
- Suspicious
- High-Risk

Features used:
- Transaction Amount
- Transaction Location

## Step 1: Import Libraries

We import required libraries for data handling, model building, and evaluation.
"""

import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

"""## Step 2: Create Dataset

We create a dataset with:
- Amount → Transaction value
- Location → 1 (same location), 0 (different location)

Labels:
- 0 → Normal
- 1 → Suspicious
- 2 → High-Risk
"""

data = [
    [5000, 1],
    [12000, 0],
    [8000, 1],
    [25000, 0],
    [15000, 0],
    [3000, 1],
    [22000, 0]
]

X = np.array(data)
y = np.array([0, 1, 0, 2, 1, 0, 2])

print("Features:\n", X)
print("Labels:\n", y)

"""## Step 3: Split Dataset

We split data into training and testing sets to evaluate model performance.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""## Step 4: Train Model

We train a Decision Tree model using the training data.
"""

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

print("Model trained successfully")

"""## Step 5: Evaluate Model

We evaluate model performance using accuracy score.
"""

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

"""## Step 6: Predict New Transactions

We test the model on new unseen transactions.
"""

new_data = np.array([
    [7000, 1],
    [18000, 0],
    [27000, 0]
])

predictions = model.predict(new_data)

categories = {
    0: "Normal",
    1: "Suspicious",
    2: "High-Risk"
}

print("\nPredictions:")
for d, pred in zip(new_data, predictions):
    print(f"Amount: {d[0]}, Location: {d[1]} → {categories[pred]}")

